version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bloo
      POSTGRES_USER: bloo
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://bloo:changeme@db:5432/bloo
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped

volumes:
  pgdata:
